[project]
name = "std"
version = "0.1.0"
main = "main.mach"
target-name = "std"
target-triple = "native"

[directories]
src-dir = "src"
dep-dir = "dep"
lib-dir = "lib"
out-dir = "out"
bin-dir = "native/bin"
obj-dir = "native/obj"

[build]
opt-level = 2
