#include <stdlib.h>
#include "token.h"

char *token_type_string(TokenType type)
{
    switch (type)
    {
    case TOKEN_ERROR:
        return "ERROR";
    case TOKEN_EOF:
        return "EOF";
    case TOKEN_USE:
        return "USE";
    case TOKEN_FUN:
        return "FUN";
    case TOKEN_STR:
        return "STR";
    case TOKEN_VAL:
        return "VAL";
    case TOKEN_VAR:
        return "VAR";
    case TOKEN_IF:
        return "IF";
    case TOKEN_OR:
        return "OR";
    case TOKEN_FOR:
        return "FOR";
    case TOKEN_BRK:
        return "BRK";
    case TOKEN_CNT:
        return "CNT";
    case TOKEN_RET:
        return "RET";
    case TOKEN_LEFT_PAREN:
        return "LEFT_PAREN";
    case TOKEN_RIGHT_PAREN:
        return "RIGHT_PAREN";
    case TOKEN_LEFT_BRACKET:
        return "LEFT_BRACKET";
    case TOKEN_RIGHT_BRACKET:
        return "RIGHT_BRACKET";
    case TOKEN_LEFT_BRACE:
        return "LEFT_BRACE";
    case TOKEN_RIGHT_BRACE:
        return "RIGHT_BRACE";
    case TOKEN_COLON:
        return "COLON";
    case TOKEN_SEMICOLON:
        return "SEMICOLON";
    case TOKEN_QUESTION:
        return "QUESTION";
    case TOKEN_AT:
        return "AT";
    case TOKEN_HASH:
        return "HASH";
    case TOKEN_DOT:
        return "DOT";
    case TOKEN_COMMA:
        return "COMMA";
    case TOKEN_PLUS:
        return "PLUS";
    case TOKEN_MINUS:
        return "MINUS";
    case TOKEN_STAR:
        return "STAR";
    case TOKEN_PERCENT:
        return "PERCENT";
    case TOKEN_CARET:
        return "CARET";
    case TOKEN_AMPERSAND:
        return "AMPERSAND";
    case TOKEN_PIPE:
        return "PIPE";
    case TOKEN_TILDE:
        return "TILDE";
    case TOKEN_LESS:
        return "LESS";
    case TOKEN_GREATER:
        return "GREATER";
    case TOKEN_EQUAL:
        return "EQUAL";
    case TOKEN_BANG:
        return "BANG";
    case TOKEN_SLASH:
        return "SLASH";
    case TOKEN_BACKSLASH:
        return "BACKSLASH";
    case TOKEN_EQUAL_EQUAL:
        return "EQUAL_EQUAL";
    case TOKEN_BANG_EQUAL:
        return "BANG_EQUAL";
    case TOKEN_LESS_EQUAL:
        return "LESS_EQUAL";
    case TOKEN_GREATER_EQUAL:
        return "GREATER_EQUAL";
    case TOKEN_LESS_LESS:
        return "LESS_LESS";
    case TOKEN_GREATER_GREATER:
        return "GREATER_GREATER";
    case TOKEN_AMPERSAND_AMPERSAND:
        return "AMPERSAND_AMPERSAND";
    case TOKEN_PIPE_PIPE:
        return "PIPE_PIPE";
    case TOKEN_NUMBER:
        return "NUMBER";
    case TOKEN_CHARACTER:
        return "CHARACTER";
    case TOKEN_STRING:
        return "STRING";
    case TOKEN_IDENTIFIER:
        return "IDENTIFIER";
    case TOKEN_COMMENT:
        return "COMMENT";
    default:
        return "UNKNOWN";
    }
}
